server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
logging.level:
  org.mybatis: debug
  org:
    springframework:
      data:
        mongodb:
          core: debug
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 1
    pathmatch:
      matching-strategy: ant_path_matcher
  view:
     suffix: .html
  messages:
    basename: i18n/Messages
  thymeleaf:
    cache: false
  application:
    name: pay-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?allowMultiQueries=true&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: "root"
      #连接池配置
    druid:
        connection-init-sqls: set names utf8mb4;
      # 初始化时建立物理连接个数
        initial-size: 10
      # 初始化时最小空闲连接池数量
        min-idle: 10
      # 最大连接池数量
        max-active: 30
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        max-open-prepared-statements: 20
        validation-query: SELECT 1
        validation-query-timeout: 6000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        keep-alive: true
        time-between-eviction-runs-millis: 300000
        keep-alive-between-time-millis: 450000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        filters: stat,slf4j,config
        #慢SQL记录,超过1s
        filter.stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        web-stat-filter:
          enabled: false
          url-pattern: /*
          # spring.datasource.druid.web-stat-filter.exclusions=
          session-stat-enable: true
          session-stat-max-count: 1000
          principal-session-name: sys_user
          principal-cookie-name: JSESSION_ID
          profile-enable: false
      # Druid监控页面配置 StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        stat-view-servlet:
          deny: ''
          enabled: false
          allow: 127.0.0.1
          url-pattern: /druid/*
          reset-enable: false
          login-username: druid
          login-password: n122WGfWj
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  path: /log
syscors.system.sysUpgrade: false

